# Generated by Django 4.2 on 2026-06-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_viprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
