# Generated by Django 4.2 on 2026-01-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_address_user_country_user_state_user_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='madoh', max_length=255),
            preserve_default=False,
        ),
    ]
