# Generated by Django 4.2 on 2026-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_otp_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
