# Generated by Django 4.2 on 2026-06-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
