# Generated by Django 4.2 on 2026-02-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_be_copied',
            field=models.BooleanField(default=False),
        ),
    ]
