# Generated by Django 4.2 on 2026-02-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/documents/'),
        ),
    ]
