# Generated by Django 4.2 on 2026-02-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='id_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
