# Generated by Django 4.2 on 2026-02-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_kyc_id_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KYC',
        ),
    ]
