# Generated by Django 4.2 on 2026-01-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('REBALANCE', 'Rebalance'), ('SWITCH', 'Strategy Switch')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
