# Generated by Django 4.2 on 2026-01-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('target_return_min', models.DecimalField(decimal_places=2, help_text='Minimum expected annual return (%)', max_digits=5)),
                ('target_return_max', models.DecimalField(decimal_places=2, help_text='Maximum expected annual return (%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['risk_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STOPPED', 'Stopped')], default='ACTIVE', max_length=10)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_allocations', to='portfolios.portfolio')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_slices', to='portfolios.holding')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
                ('strategy_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_holdings', to='strategies.portfoliostrategy')),
            ],
            options={
                'unique_together': {('strategy_allocation', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='StrategyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='strategies.strategy')),
            ],
            options={
                'unique_together': {('strategy', 'asset')},
            },
        ),
    ]
