# Generated by Django 4.2 on 2026-01-17 13:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyholding',
            name='average_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
    ]
