# Generated by Django 4.2 on 2026-01-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['risk_level', 'name']},
        ),
        migrations.AddField(
            model_name='strategy',
            name='target_return_max',
            field=models.DecimalField(decimal_places=2, default=6, help_text='Maximum expected annual return (%)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='target_return_min',
            field=models.DecimalField(decimal_places=2, default=4, help_text='Minimum expected annual return (%)', max_digits=5),
            preserve_default=False,
        ),
    ]
