# Generated by Django 4.2 on 2026-01-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0003_copyrelationship_allocated_cash'),
        ('strategies', '0002_strategyholding_average_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostrategy',
            name='copy_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copied_strategies', to='copytrading.copyrelationship'),
        ),
    ]
