# Generated by Django 4.2 on 2026-02-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_portfoliostrategy_remaining_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('CRYPTO', 'Trade Crypto'), ('STOCK', 'Trade Stock'), ('REIT', 'Invest in REIT')], default='STOCK', help_text='Type of strategy', max_length=20),
        ),
    ]
