# Generated by Django 4.2 on 2026-01-30 13:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_tradeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='min_trade_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('1E-8'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('REIT', 'REIT'), ('CRYPTO', 'Crypto')], max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=8, default=Decimal('100.00'), max_digits=20),
        ),
    ]
