# Generated by Django 4.2 on 2026-02-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_is_tradeable_asset_min_trade_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('REIT', 'REIT'), ('CRYPTO', 'Crypto')], max_length=10),
        ),
    ]
