# Generated by Django 4.2 on 2026-03-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='wallet_qr/')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='transaction.coin')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.coin'),
        ),
    ]
