# Generated by Django 4.2 on 2026-03-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_coin_wallet_alter_transaction_coin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='icon',
            field=models.ImageField(blank=True, upload_to='coin_icons/'),
        ),
        migrations.AddField(
            model_name='coin',
            name='network',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
