# Generated by Django 4.2 on 2026-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_payment_method_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3, null=True),
        ),
    ]
