# Generated by Django 4.2 on 2026-03-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_coin_icon_coin_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.coin'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin_type',
            field=models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT')], max_length=10, null=True),
        ),
    ]
