# Generated by Django 4.2 on 2026-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
