# Generated by Django 4.2 on 2026-03-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_coin_alter_transaction_coin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='coin_icons/'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
