# Generated by Django 4.2 on 2026-03-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_coin_icon_alter_coin_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='icon',
        ),
    ]
