# Generated by Django 4.2 on 2026-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coin_type',
            field=models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT')], max_length=10, null=True),
        ),
    ]
