# Generated by Django 4.2 on 2026-03-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_remove_coin_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='coin_icons/'),
        ),
    ]
