# Generated by Django 4.2 on 2026-03-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_coin_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='coin_type',
        ),
    ]
