# Generated by Django 4.2 on 2026-03-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_remove_transaction_coin_type'),
    ]

    operations = [
    ]
