# Generated by Django 4.2 on 2026-09-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('DIVIDEND', 'Dividend'), ('REBALANCE', 'Rebalance'), ('LIQUIDATION', 'Liquidation')], max_length=20),
        ),
    ]
