# Generated by Django 4.2 on 2026-03-08 13:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('plan', '0004_orderplan_is_mirrowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('remaining_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('trade_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('min_balance', models.DecimalField(decimal_places=2, default=Decimal('800.00'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='customer.portfolio')),
                ('last_copied_orderplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.orderplan')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='customer.portfolio')),
            ],
            options={
                'unique_together': {('follower', 'leader')},
            },
        ),
        migrations.CreateModel(
            name='CopyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower_orderplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_trades', to='plan.orderplan')),
                ('leader_orderplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_trades', to='plan.orderplan')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_trades', to='copytrade.copyrelationship')),
            ],
            options={
                'unique_together': {('relationship', 'leader_orderplan')},
            },
        ),
    ]
