# Generated by Django 4.2 on 2026-03-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='long_description',
            field=models.TextField(blank=True, help_text='A detailed description of the product.', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='short_description',
            field=models.CharField(blank=True, help_text='A brief summary of the product (max 255 characters).', max_length=255, null=True),
        ),
    ]
