# Generated by Django 4.2 on 2026-03-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_long_description_plan_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plantype',
            field=models.CharField(choices=[('CRYPTO', 'Crypto'), ('REIT', 'Reit'), ('STOCK', 'Stock'), ('ASSET_MANDATES', 'Asset Mandates')], default='CRYPTO', max_length=30),
        ),
    ]
