# Generated by Django 4.2 on 2026-02-13 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0003_plan_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('after_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='plan.orderplan')),
            ],
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['order_plan', 'created_at'], name='plan_transa_order_p_1ee4c3_idx'),
        ),
    ]
