# Generated by Django 4.2 on 2026-03-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_plan_plantype'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplan',
            name='is_mirrowed',
            field=models.BooleanField(default=False),
        ),
    ]
