# Generated by Django 4.2 on 2026-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_orderplan_is_mirrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plan_img/'),
        ),
    ]
