# Generated by Django 4.2 on 2026-04-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_plan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='numbering',
            field=models.IntegerField(default=1),
        ),
    ]
