# Generated by Django 4.2 on 2026-04-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_plan_numbering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['numbering']},
        ),
        migrations.AddField(
            model_name='plan',
            name='backing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='blueprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='strategy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
