# Generated by Django 4.2 on 2026-07-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_alter_plan_options_plan_backing_plan_blueprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplan',
            name='yield_percent',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Daily percent (e.g., 0.5000 for 0.5%)', max_digits=6),
        ),
    ]
