# Generated by Django 4.2 on 2026-07-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_orderplan_yield_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplan',
            name='yield_percent',
            field=models.DecimalField(decimal_places=4, default=4.0, help_text='Daily percent (e.g., 0.5000 for 0.5%)', max_digits=6),
        ),
    ]
