# Generated by Django 4.2 on 2026-01-17 08:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopyTradePnL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
