# Generated by Django 4.2 on 2026-01-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0004_alter_portfoliosnapshot_options_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='portfolios.portfolio')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='portfolios.portfolio')),
            ],
            options={
                'unique_together': {('follower', 'leader')},
            },
        ),
    ]
