# Generated by Django 4.2 on 2026-01-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copytrading', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytradepnl',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_pnls', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='copytradepnl',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_copy_pnls', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='copyrelationship',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='copyrelationship',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='portfolios.portfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='copytradepnl',
            unique_together={('follower', 'leader')},
        ),
        migrations.AlterUniqueTogether(
            name='copyrelationship',
            unique_together={('follower', 'leader')},
        ),
    ]
