# Generated by Django 4.2 on 2026-01-18 09:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0003_copyrelationship_allocated_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrelationship',
            name='remaining_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
